opencti:
  url: 'http://localhost'
  token: '64694d09-67cd-4d97-b49f-bb2095a5854a'
  
connector:
  id: 'f4c54571-4f01-4ac5-8495-eae51748872e'
  type: 'EXTERNAL_IMPORT'
  name: 'Talos IP blacklist'
  scope: 'ipv4-addr'
  confidence_level: 3
  log_level: 'info'
  
talosip:
  max_tlp: 'TLP:AMBER'
  url: 'https://talosintelligence.com/documents/ip-blacklist'
  interval: 7