version: '3'
services: 
    connector-myconnector:
        image:
        environment: 
            - OPENCTI_URL=http://localhost
            - OPENCTI_TOKEN=ChangeMe
            - CONNECTOR_ID=ChangeMe
            - CONNECTOR_TYPE=EXTERNAL_IMPORT
            - CONNECTOR_NAME=VirusTotal
            - CONNECTOR_SCOPE='ipv4-addr'
            - CONNECTOR_CONFIDENCE_LEVEL=3
            - CONNECTOR_LOG_LEVEL=info
            - TALOSIP_MAX_TLP=TLP:AMBER
            - TALOSIP_URL='https://talosintelligence.com/documents/ip-blacklist'
            - TALOSIP_INTERVAL= 7
          restart: always