version: '3'
services: 
    connector-talosip:
        image: phucsnguyenv/connector-talosip:latest
        environment:
          - OPENCTI_URL=http://opencti:8080
          - OPENCTI_TOKEN=ChangeMe
          - CONNECTOR_ID=ChangeMe
          - CONNECTOR_TYPE=EXTERNAL_IMPORT
          - CONNECTOR_NAME=Talos IP Blacklist
          - CONNECTOR_SCOPE=ipv4-addr
          - CONNECTOR_CONFIDENCE_LEVEL=3
          - CONNECTOR_UPDATE_EXISTING_DATA=true
          - CONNECTOR_LOG_LEVEL=info
          - TALOSIP_URL=https://talosintelligence.com/documents/ip-blacklist
          - TALOSIP_INTERVAL=1 # Days
        depends_on: 
          - opencti
        restart: always