version: '3'
services: 
    connector-fireeye:
        image: phucsnguyenv/connector-fireeye:latest
        volumes: 
          - ChangeMe:/opt/opencti-connector-fireeye/data/
        environment:
          - OPENCTI_URL=http://opencti:8080
          - OPENCTI_TOKEN=ChangeMe
          - CONNECTOR_ID=ChangeMe
          - CONNECTOR_TYPE=EXTERNAL_IMPORT
          - CONNECTOR_NAME=FireEye data importer
          - CONNECTOR_SCOPE=ipv4-addr,domain,url,file-md5,file-sha1,file-sha256
          - CONNECTOR_CONFIDENCE_LEVEL=1
          - CONNECTOR_UPDATE_EXISTING_DATA=true
          - CONNECTOR_LOG_LEVEL=info
          - INTERVAL_SCAN=123
          - REPORT_ID=ChangeMe
        depends_on: 
          - opencti
        restart: always