version: '3'
services: 
  connector-virustotal-reference:
    image: phucsnguyenv/connector-virustotal-reference:latest
    environment: 
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=Virustotal External Reference Add
      - CONNECTOR_SCOPE=domain,ipv4-addr,url,file-md5,file-sha1,file-sha256
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on: 
      - opencti