version: '3'
services: 
    connector-internal-import:
        image: phucsnguyenv/connector-internal-import
        volumes: 
          - ChangeMe:/opt/opencti-connector-internal-import/data/
        environment:
          - OPENCTI_URL=http://opencti:8080
          - OPENCTI_TOKEN=ChangeMe
          - CONNECTOR_ID=ChangeMe
          - CONNECTOR_TYPE=EXTERNAL_IMPORT
          - CONNECTOR_NAME=Adding external ref
          - CONNECTOR_SCOPE=ipv4-addr,domain-name,url,file-md5,file-sha1,file-sha256
          - CONNECTOR_CONFIDENCE_LEVEL=3
          - CONNECTOR_UPDATE_EXISTING_DATA=true
          - CONNECTOR_LOG_LEVEL=info
        depends_on: 
          - opencti
        restart: always